version: '3.8'
services:
  db:
    image: postgres:15
    container_name: travelplanner_postgres
    environment:
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: travel_pass
      POSTGRES_DB: travel_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "travel_user"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data: 